name = "cedh-bcs-dashboard"
compatibility_date = "2025-09-29"

[site]
bucket = "./dist"

[site.upload]
format = "service-worker"

[env.production]
route = "estadisticas.cedhbcs.org.mx/*"
zone_id = ""  # Necessitaràs afegir el teu zone_id de Cloudflare